#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


hdmi=$(xrandr |grep ' connected' |grep 'HDMI' |awk '{print $1}')

[[ -z "$hdmi" ]] &&
bspc monitor eDP-1 -d 1 2 3 4 5

[[ ! -z "$hdmi" ]] &&
bspc monitor HDMI-1 -d 1 2 3 4 5 &&
bspc monitor eDP-1 -d 6 7 8 9 10 &&
bspc config -m HDMI-1 left_padding 8

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color '#010713'
bspc config focused_border_color '#222632'

feh --bg-scale ~/.config/bspwm/wallpaper-1.png &
setxkbmap -layout 'us,ru' -option 'grp:caps_toggle' &
bash ~/.config/polybar/launch.sh &
