#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d I II III
bspc monitor eDP-1 -d I II III VI V

bspc config -m HDMI-1 top_padding 13
bspc config -m HDMI-1 left_padding 9
bspc config -m HDMI-1 right_padding 9

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color '#010713'
bspc config focused_border_color '#222632'

feh --bg-scale ~/.config/bspwm/wallpaper-2.png &
setxkbmap -layout 'us,ru' -option 'grp:caps_toggle' &
bash ~/.config/polybar/launch.sh &
